//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppGestionStock
{
    using System;
    using System.Collections.Generic;
    
    public partial class produit
    {
        public int ipProduit { get; set; }
        public string codeProduit { get; set; }
        public string denominationProduit { get; set; }
        public int qte { get; set; }
        public int pu { get; set; }
        public int idC { get; set; }
        public int qteMinimum { get; set; }
        public int qteCritique { get; set; }
        public string image { get; set; }
        public string description { get; set; }
    }
}
